//// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
//using System;
//using System.Collections.Generic;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Metadata;

//namespace NewsletterSignupDemo.Models
//{
//    public partial class NewsletterContext : DbContext
//    {

//        private protected string _connectionString;

//        public NewsletterContext(string connectionString)
//        {
//            _connectionString = connectionString;
//        }

//        public NewsletterContext(DbContextOptions<NewsletterContext> options)
//            : base(options)
//        {
//        }

//        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//        {
//            optionsBuilder.UseSqlServer(_connectionString);
//        }

//        public virtual DbSet<contact> contacts { get; set; }